server.port=0
spring.application.name=OrderService
spring.devtools.restart.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8010/eureka/
eureka.instance.instanceId=${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

spring.config.import = optional:file:../../.env[.properties]
# PostgreSQL datasource (use env.properties to provide placeholders)
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Use PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

## LINE Pay
linepay.channel-id=${LINEPAY_CHANNEL_ID}
linepay.channel-secret=${LINEPAY_CHANNEL_SECRET}
linepay.base-url=https://sandbox-api-pay.line.me
linepay.request-uri=/v3/payments/request
linepay.base-uri=/v3/payments