spring.application.name=DiscoveryService

server.port=8010
eureka.instace.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.default-zone=http://${eureka.instace.hostname}:${server.port}/eureka/
